pipeline {
    agent any

    parameters {
        booleanParam(name: 'Delay', defaultValue: false, description: 'Deploy to production environment?')
    }

    stages {
        stage('Build') {
            steps {
                echo "Build number : ${env.BUILD_NUMBER}"
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    if (params.Delay == true) {
                        echo 'Hello World!'
                        // Add your deployment commands here
                    } else {
                        error('Delay is set to false. Failing the pipeline.')
                    }
                }
            }
        }
        
        stage('Approval') {
            // Using Declarative Input Directive (Cleanest way)
            input {
                message 'Do you want to proceed with the manual deployment?'
                ok 'Proceed'
                id 'DeployInput'
            }
            steps {
                script{
                    def pythonExecutable = '"C:\\Users\\HARRISH C\\AppData\\Local\\Python\\bin\\python.exe"'
                    echo "Approval granted. Continuing pipeline..."
                    git url: 'https://github.com/HarrishC/jenkins_testing.git', branch: 'main'
                    dir('New Jenkins pipeline') {
                        bat pythonExecutable + ' helloWorld.py'
                    }
                }
            }
        }

    }
}
